### GRL.py

In [4]:
import torch
from GRL import ReverseLayerF

In [23]:
feature = torch.rand(3, dtype=torch.float32, requires_grad=True)
x = torch.arange(3, 6)
x

tensor([3, 4, 5])

In [24]:
# at the propogation stage, we just use an identical mapping.
# NOTED that you can set the alpha to adjust your need.
feature_rev = ReverseLayerF.apply(feature, 1)
feature_rev

tensor([0.4069, 0.8363, 0.9379], grad_fn=<ReverseLayerFBackward>)

In [25]:
# clear all the grad
feature.grad = torch.zeros(feature.shape)

loss = feature_rev * x - 8
loss_sum = torch.sum(loss)

# at the back-prop stage, an GRL is set to reversal the grad.
loss_sum.backward()
feature.grad

tensor([-3., -4., -5.])

### 父类和子类的构造函数调用问题

In [3]:
class Parent:
    def __init__(self):
        print("Parent construct function called")
        self.name = "parent"

class Child1(Parent):
    def __init__(self):
        print("Child construct function called")

Child1()

Child construct function called


In [4]:
class Child2(Parent):
    def __init__(self):
        # 显式调用
        super().__init__()
        print("Child construct function called")

Child2()

Parent construct function called
Child construct function called
